name: Continuous integration
on: [push, pull_request]

jobs:
  test:
    name: cargo test (${{ matrix.toolchain }}, ${{ matrix.features }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, "1.85.1"]
        features: ["--all-features", "--no-default-features"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - run: RUST_LOG=trace cargo test ${{ matrix.features }} --release
      - run: cargo clippy ${{ matrix.features }} -- -D warnings